baseURL = 'https://zarate02.github.io/'
languageCode = 'en-us'
title = 'hpyYh Blog'
enableRobotsTXT = true
#theme = 'pehtheme-hugo'

summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
disqusShortname = 'https-zarate02-github-io' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = ['devops', 'anime']

	[params.author]
		name = 'hpyYh'
#		bio = 'for happiness! for technology!'
		avatar = '/images/profile.png'
		twitter = 'https://twitter.com/insertapps'

[pagination]
	pagerSize = 6 # <- Set the desired number of posts per page 

[menu] # Menu management
	[[menu.main]]
		name = 'DevOps'
		pageRef = '/devops'
		weight = 10
	[[menu.main]]
		name = 'Anime'
		pageRef = '/anime'
		weight = 15
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 25

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[outputs]
    home = ["HTML", "RSS", "JSON"]
    section = ["HTML"]              # 섹션에서는 제거
    page = ["HTML"]                 # 페이지에서도 제거

[related]
    includeNewer = true
    threshold    = 20
    [[related.indices]]
        name = "tags"
        weight = 100
    [[related.indices]]
        name = "categories"
        weight = 80